### ISSUE TITLE
[BUG] Component tree isn't build correctly

### ISSUE THREAD

**Issue by enaoki** [microsoft/accessibility-insights-windows#1166]
**Describe the bug**
Components tree isn't build when mouse is over Power BI Desktop installed in a Windows Server.

**To Reproduce**
1. In a Windows Server machine;
2. Open Power BI Desktop;
3. Open Accessibility Insights;
3. Mouse over the Power BI Desktop application;

**Expected behavior**
The component tree should be build as it is in a Windows 10 machine.

**Actual behavior**
The component tree isn't build.

**Screenshots or .GIF**
OK in Windows 10
![image](https://user-images.githubusercontent.com/8048700/127216728-89023445-9d72-4643-b3fd-10f89472e65c.png)

NOK in Windows Server 2019 Datacenter
![image](https://user-images.githubusercontent.com/8048700/127216924-0b044642-d972-40cd-989f-02d41792d2e5.png)

**Desktop (please complete the following information):**
 - OS: Windows Server 2019 Version 1809 (OS Build 17763.2061)
 - Accessibility Insights for Windows Version: 1.1.1663.1
 - Target Application: Power BI Desktop
 - Target Application Version: 2.95.804.0 64-bit (July 2021)

**Additional context**
I could reproduce the same behavior in prior versions: Windows Server 2012 R2 and 2016. Just want to confirm if there is some restrictions regarding Windows Server. Couldn't find anything similar in SO.

**Comment by DaveTryon** [comment]
Hi, @enaoki! 

  You ask if Accessibility Insights for Windows treats the client or server OS versions differently. We don't, but since we're simply reporting information that we receive from UIA, it's possible that OS-specific factors could be influencing the data that we receive.

  The first suggestion would be to enable UIAccess on the server version. UIAccess is a special security permission that allows accessibility tools to obtain data from all applications on the system. Instructions to enable UIAccess are listed in the [FAQ](https://accessibilityinsights.io/docs/en/windows/reference/faq/#sometimes-accessibility-insights-for-windows-cant-find-my-application-is-there-a-fix). This requires you to have administrative permissions on the machine.

  The second suggestion (if UIAccess doesn't help) would be to run an automated check against the entire application (Select "Entire app" from the "What to select" control), hover the mouse over the PowerBI Desktop app, then press Shift+F8. This will trigger automated tests against the app. Once the test results are displayed, click the button labeled "View results in the UI Automation tree", click on the "Details" tab, and then look for the control in the hierarchy view. The contents will reflect the state of the application when the tests were run. With some apps, we have difficulty traversing the full UIA tree in live inspect mode, but automated checks mode get everything. You lose some functionality (such as listening for events or using pattern methods) this way, but it gets past the problem of not being able to inspect all of the UIA elements.

  Another option might be to go into the settings tab, disable "Selection by mouse hover", save the changes, then see if you have better luck selecting controls (such as the ribbon item) using keyboard focus. This option is obviously limited to controls that are focusable, but it's sometimes more reliable than selecting controls by mouse hover.

  Please let us know if any of these help, so that we can have the information for future use. Thanks!

[Dave Tryon](https://github.com/DaveTryon)
Accessibility Insights team

**Comment by enaoki** [comment]
Hi @DaveTryon! Thanks for the suggestions.

Follow below the results from each one.

1. Enabling UIAccess didn't help. Tried running as administrator as well.

![image](https://user-images.githubusercontent.com/8048700/127236910-90019b73-80a4-4ed0-a709-634f24fdb4c3.png)

2. Using Entire app result:

![image](https://user-images.githubusercontent.com/8048700/127232411-7cea43d9-1340-4733-b05f-43adf5287f52.png)

And the tests:

![image](https://user-images.githubusercontent.com/8048700/127232760-9ac22fea-f626-4733-ae13-fde6519f03b4.png)

3. Disable the "Selection by mouse hover" couldn't help either.

**Comment by DaveTryon** [comment]
@enaoki, thanks for checking. After installing PowerBI Desktop locally, I figured out what is happening here:

1. The PowerBI Desktop app is Chromium-based. You can confirm this on your non-server machine by looking for the **Framework** property, which reports **Chrome**.
2. Chromium supports the `IAccessible2` interface for automation/accessibility, but it doesn't support UI Automation, which has been the Windows native accessibility framework since 2005. Accessibility Insights supports only UI Automation, not `IAccessible2`.
3. Windows 10 version 1903 added a layer to dynamically convert between `IAccessible2` and UI Automation.
4. Your desktop machine is on 20H2, so it has the conversion layer. Your server machine is on Windows 1809, so it _doesn't_ have the conversion layer. As a result, UI Automation on the server exposes a lot less data, and that difference is showing up in Accessibility Insights for Windows.

This class of problem is referenced in this [FAQ issue](https://accessibilityinsights.io/docs/en/windows/reference/faq/#does-accessibility-insights-for-windows-work-with-chromium-or-electron-apps), although the missing piece here was the fact that PowerBI Desktop is Chromium-based.

I can offer 2 ways to get parity between your 2 machines:
1. Update the server machine to release 1903 or newer. That may not be feasible, depending on what else you have running on the machine, as well as potentially requiring a clean install if you're on the LTS release channel.
2. Install a newer version of Windows 10 in a VM that runs on the server machine, then run both PowerBI Desktop and Accessibility Insights for Windows inside the VM.

There are obvious downsides to either approach, but this is external to Accessibility Insights and there's not really anything that we can do about it...

Please close this issue out if you feel that we've answered your question. Thanks!

[Dave Tryon](https://github.com/DaveTryon)
Accessibility Insights team

**Comment by enaoki** [comment]
Yep, you did! Thanks for all clarification!
