### ISSUE TITLE
[Feature Request] Create a Means to Disable Telemetry During Install

### ISSUE THREAD

**Issue by auldydrums** [microsoft/accessibility-insights-windows#1182]
**Describe the solution you'd like**

A means to disable telemetry during the install process, either by a means of an argument we can pass through with the MSI or via registry entry that could be amended post install (either at the end of the install script or via group policy) 

**Additional context**

This was identified as a nice to have by our info sec manager. We have a workaround by means of bombarding the users with prompts before installation and at installation completion however taking the disabling of telemetry from the end user would be preferable.

**Comment by DaveTryon** [comment]
We've discussed this a bit, and @dbjorge's proposal won't work in the multi-user scenario. We think we've settled on a design for this:

1. Designate a registry setting that requires admin privileges to write. If this setting exists, AIWin telemetry will be disabled for all users. Bonus points if we choose a location that can easily be set by group policy
2. Add code to the client so that if this registry key is set, we expose to the user that telemetry has been disabled by their organization so they can't enable it. Potentially impacted dialogs: First-boot telemetry, settings.
3. We probably won't modify the setup to write this key, but we can document it for organizations that are sensitive to telemetry leaving the machine

A simple implementation should be easy to complete in a day or two.

**Comment by DaveTryon** [comment]
@auldydrums This feature is now in the Canary release available at https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.1733.01. it will be in our next Production release (hopefully in October). Note that we chose _not_ to set the registry key via setup, as most organizations that would use this feature already have mechanisms in place to create registry keys.

Please take a look then close as your convenience. Thanks!
