### ISSUE TITLE
Toasts show incorrect title text value in Accessibility Insights

### ISSUE THREAD

**Issue by amit-msft** [microsoft/accessibility-insights-windows#1190]
1. Download notification visualizer app https://www.microsoft.com/en-us/p/notifications-visualizer/9nblggh5xsl1?activetab=pivot:overviewtab
2. Open Accessibility Insights
2. Open any notification type template ex. Basic
3. Trigger a toast by clicking on "Pop toast"
4. Hover over the toast & observe values in Acc insights
5. Change the text in the toast template XML in Notification visualizer, ex. for Basic.xml - change "Hello world" to "foobar"
6. Trigger a toast by clicking on "Pop toast"
7. Hover over the toast & observe values in Acc insights

Expected: Acc Insights should read "foobar" for title text
Actual: Acc Insights reads "Hello world" (or some other value from a previous toast) for title text

Windows Narrator reads the text as exepcted. Repros only in Accessibility insights.

Repros on Windows 11. Does not repro on Windows 10.

**Comment by karanbirsingh** [comment]
@amit-msft Hi Amit, thanks for filing the issue. I was able to reproduce this today. In Windows 10 the Toast UIA representation is correct. In Windows 11, the text node is not updated with subsequent Toast updates. I also explored the toast using [inspect.exe](https://docs.microsoft.com/en-us/windows/win32/winauto/inspect-objects), a legacy UIA client - it shows the same behavior, so I believe Accessibility Insights is providing accurate UIA information. Narrator announces the new name because the Window name is updated properly. I recommend getting in touch with the Toast UI owners + UIA to investigate this further.
