### ISSUE TITLE
[BUG] An onscreen element must not have a null BoundingRectangle property - false failure

### ISSUE THREAD

**Issue by RolandLeFranc** [microsoft/accessibility-insights-windows#1283]
**Describe the bug**
**Accessibility Insights** reports a **An onscreen element must not have a null BoundingRectangle property error** for every clickable or focusable element pushed out of windows that is contained in a scrollable control that is partially on window. Looking to confirm that it is a false failure, and fix the tool to not report them.

**To Reproduce**
1. Build a minimalistic UWP C# repro app with the following XAML:
```
<Page
    <Grid>
        <ScrollViewer>
            <TextBlock FontSize="48" TextWrapping="Wrap">
                <Run>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</Run>
                <Hyperlink NavigateUri="https://www.google.com/">www.google.com</Hyperlink>
            </TextBlock>
        </ScrollViewer>
    </Grid>
</Page>
```
2. Run the app. Reduce the width of the app to push the www.google.com hyperlink out of window
3. Start Accessibility Insights. Run automated test on the entire app
4. Receive the **An onscreen element must not have a null BoundingRectangle property** for the `link www.google.com` element

**Expected behavior**
We expect this plain XAML code to pass the full Accessibility Insights test with no failures.

**Actual behavior**
We receive a **An onscreen element must not have a null BoundingRectangle property** error as soon as the app is not large enough to display the focusable element.

**Screenshots or .GIF**
1. Screenshot Case 1 with no failure if the app window is large enough to display the hyperlink on screen
2. Screenshot Case 2 with the failure if the app window is too small and doesn't display the hyperlink on screen

![Repro-Case1](https://user-images.githubusercontent.com/10080136/151223758-8b1a4e7c-8339-4b94-acec-b13a39e2c205.png)
![Repro-Case2](https://user-images.githubusercontent.com/10080136/151223734-847dc2e6-b4bc-4815-9a4e-490302d5a3ec.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 19044
 - Accessibility Insights for Windows Version:  1.7.1741.1
 - Target Application: UWP
 - Target Application Version: -

**Additional context**
Priority requested -

**Comment by DaveTryon** [comment]
Thanks for the report, @RolandLeFranc! This isn't a false positive, because the off-screen HyperLink's `IsOffScreen` property is reported as `false` when it should be reported as `true` (see [this page](https://docs.microsoft.com/en-us/dotnet/api/system.windows.automation.automationelement.automationelementinformation.isoffscreen?view=windowsdesktop-6.0) for more details on the IsOffScreen property).

This behavior is a known bug in UWP, and is tracked at https://github.com/microsoft/microsoft-ui-xaml/issues/5666. You might want to chime in on that thread to see if community interest will bump it up the priority stack. It might even be possible to contribute a fix if you feel so inclined.

Please close out this issue if you agree that what you're seeing is consistent with the reported issue in UWP. Thanks!

**Comment by RolandLeFranc** [comment]
Thank you @DaveTryon for the great and quick response. Yes, this is the bug that we see. I am closing this bug. Great job on the tool!

**Comment by RolandLeFranc** [comment]
This issue is not a tool false failure - it is due to a known XAML bug.
