### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by XamlTest** [microsoft/accessibility-insights-windows#1336]
**Describe the bug**
accessibility tools updated errors
![image](https://user-images.githubusercontent.com/97647558/167803411-ccc852a4-cbef-4d61-a4db-9972964ff8fe.png)
I can't open the file issue 

**To Reproduce**
1. Accessibility tool update for [https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.1934.01](url)
2. Run accessibility tool
3. Error in accessibility insights for windows
4. Click on file issue

**Expected behavior**
I can open the file issue when I click on it. 

**Actual behavior**
I can't open the file issue when I click on it. 

**Desktop (please complete the following information):**
 - OS:Windows 10 21H1
 - Accessibility Insights for Windows Version:1.1.1934.1

**Comment by JGibson2019** [comment]
Hi @XamlTest; when you're attempting to file an issue, are you trying to file with an ADO board?

**Comment by DaveTryon** [comment]
@xamltest, the error screen indicates that the requested query string is too long. The ADO API that we use to open bugs imposes a limit or 2000 characters on the length of the query string. We have code to ensure that we're below the 2000 character limit, so it normally works. It has been known to break, however, when the call to ADO also triggers the login redirect, which can push the query parameters beyond the 2000 character limit.

There are a couple of workarounds:
1. Try making your first bug to ADO something with minimal text, like those reported as "The Name property of a focusable element must not be null"
2. Use Edge to connect to ADO _before_ starting AIWin, so that the Single Sign-On authentication is already available when AIWin starts up.

It might be possible for AIWin to allocate some "redirect buffer space" when we consider the query string limit, at the expense of losing information that would otherwise be included in the bug report. This would ultimately be based on a heuristic, so it still wouldn't solve every case. As you might imagine, that wouldn't be our preferred option...
