### ISSUE TITLE
[BUG] Reference to Unofficial.Microsoft.mshtml

### ISSUE THREAD

**Issue by drasticactions** [microsoft/accessibility-insights-windows#1377]
Hey folks,

I was going through the third-party notices for this app and saw that "Unofficial.Microsoft.mshtml" is being referenced.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/898335/176783939-f129a00c-e4ad-4d30-8ee6-c6ade150de09.png)

https://github.com/microsoft/accessibility-insights-windows/blob/main/src/AccessibilityInsights.Extensions.AzureDevOps/Extensions.AzureDevOps.csproj#L39

This library (https://github.com/ogaudefroy/Unofficial.Microsoft.mshtml) is an "Unofficial" repack of "Microsoft.mshtml.dll", a Microsoft-built library. I believe it's the original IE rendering engine? I'm confused why a Microsoft branded product would need to use an "unofficial" nuget? It's also marked as MIT licensed, which (IMO) is kinda silly, as that person can make no such claims to it. They don't own the original library.

Is this actively being used? Could this be a vestige of something earlier? It was inserted two years ago.

**Comment by DaveTryon** [comment]
@drasticactions, we've merged a fix for this. It will appear in Canary build 1.1.2014.1, due to be published at https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.2014.01 on July 8th. Please regress the issue once the release is available and close out at your convenience. Thanks!
