### ISSUE TITLE
[General Question] How does the automatic color picker work?

### ISSUE THREAD

**Issue by salux** [microsoft/accessibility-insights-windows#1403]
**We encourage tool related questions to be asked on stackoverflow.com and tagged with `accessibility-insights`.**

**Your question here**
We're seeing odd foreground colors when using the automatic color detection feature of the tool. I suspect that it's picking up anti-aliasing colors instead of the color defined in code. A colleague grabbed this screenshot of a default MFC combobox where the foreground color is white, but the tool detects it as a light blue.
![DefaultMFCCombo](https://user-images.githubusercontent.com/7938225/184404488-3160434a-650d-4914-9912-9b2f8037e8e5.png)

We also saw an even stranger example where it detects a sort of eggplant purple color when looking at black text on a white background (note that this didn't seem consistent as sometimes it reported black-over-white and sometimes it was purple-over-white). I grabbed a screenshot of this and when I zoomed into the anti-aliased text, I found a match for the purple. Strange, strange.

So, are we using the tool wrong? Is there some magic to getting it to use the coded colors vs picking one of the anti-alias colors used for the text? Our team is trying to ensure the project is accessible, but when the tool gives unexpected results, we're not sure how to deal with it.

**Comment by DaveTryon** [comment]
Hello, @salux! You're correct in suspecting that the anti-aliasing is skewing the results. UIA doesn't provide us with a way to directly query colors, so we have to infer them. The general pattern is to grab the bitmap represented by the control's bounding rectangle, then analyze the bitmap. As called out in #996, our logic isn't perfect. The code itself is in Axe.Windows' [ColorContrastAnalyzer.RunColorContrastCalculation](https://github.com/microsoft/axe-windows/blob/main/src/Desktop/ColorContrastAnalyzer/ImageCollection.cs#L40) method, which has 2 versions. The V1 implementation (what we're currently using) was ported from an Android implementation, where the DPI is high compared to the text size, and where CPU and memory can be very limited. In Windows, the DPI is much lower compared to the text size, and that's the root cause of what you're seeing here. We've written (but not yet switched to using) a V2 implementation that tends to give better results but is more performance-intensive. We need to some more work here to find a good balance between accuracy and reasonable perf. It's on the backlog, but it's not high on the priority list. Please feel free to upvote the existing issue and hopefully that will bump it up the priority list a bit.

If this answers your question, please feel free to close out this issue. Thanks!

**Comment by salux** [comment]
Yes, this makes sense. Also, I commented on https://github.com/microsoft/accessibility-insights-windows/issues/996 and received another confirmation that we all know it can be improved... it's just a matter of prioritization. In the meantime, using the color picker or the values actually in the display code will have to suffice.

Thanks!
