### ISSUE TITLE
Users aren't aware that they can go back to test mode after selecting "View results in UIA tree"

### ISSUE THREAD

**Issue by risanaka** [Microsoft/accessibility-insights-windows#145]
**Describe the bug**
When a user selects "View results in UIA tree" in Automated checks, the user is taken to Live Inspect's Test Results view with limited insight into where they are and how they can get back to the automated checks results.

**To Reproduce**
1. Start a screen reader.
2. Launch Accessibility Insights for Windows.
3. Run automated checks on an element/app.
4. In Accessibility Insights for Windows, select "View results in UIA Tree".

**Expected behavior**
All users should know that they've been taken to Live Inspect's Test Results view, and that they can get back to the automated checks results by navigating to the Test mode or via the breadcrumbs.

**Actual behavior**
User study feedback suggests folks are unaware that they can go back to the Test mode.

**Screenshots or .GIF**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809] (Get the version by running `winver` from the command line)
 - Accessibility Insights for Windows Version:
 - Target Application: [e.g. chrome, safari]
 - Target Application Version: [e.g. 22]

**Additional context**
Priority requested -

**Comment by neocln** [comment]
@risanaka @cheade any update on this?

**Comment by cheade** [comment]
@risanaka 

I don't have any quick fixes for this one other than changing what we announce to users, and if we can add in extra verbiage to assist them. 

I know the UX navigation on this has been a problem since I started. We had gone through several months of different iterations of how we can fix the navigation but none of them, from what I understand, are quick fixes. 

For screen readers is there a way to put in an added announcement? (Current screen: list of failures found grouped by rule ID), and when they switch to the errors in the UI Automation tree (Current screen: Paused UI Automation tree with error overlay). I'm not sure where we'd announce to them that they can go back using the breadcrumb. Is this something that they'd come across as they begin to navigate the page? Or is it that they come to it but it's not clear that's how to navigate?

**Comment by risanaka** [comment]
Closing this issue as there's a larger discussion required on whether we need a teaching UX capability in Accessibility Insights.
