### ISSUE TITLE
[BUG] Issue filing missing from recent builds

### ISSUE THREAD

**Issue by jalkire** [Microsoft/accessibility-insights-windows#267]
**Describe the bug**
Issue filing is completely absent from recent builds.

**To Reproduce**
1. Install and launch [Canary Release: v1.1.0827.01](https://github.com/Microsoft/accessibility-insights-windows/releases/tag/v1.1.0827.01)
2. Note that there is no issue icon on the bottom left
3. Note that is no Connections tab in settings
4. Note that there is no File issue button anywhere in the ux.

**Expected behavior**
Issue filing should be available from the ux.

**Actual behavior**
Issue filing is not available. 

**Screenshots or .GIF**
![image](https://user-images.githubusercontent.com/4615491/55743701-d822fd80-59e7-11e9-8030-bb39b5a139c6.png)

**Comment by neocln** [comment]
@jalkire @karanbirsingh are all extension files at the correct location?

**Comment by karanbirsingh** [comment]
@neocln It seems this issue was introduced in PR #253 based on MSI builds before & after the change. Looking in more detail

**Comment by neocln** [comment]
this may be a rootcause of this issue. 
Activated	Event	Time	Duration	Thread
Activated Historical Code Context	Exception thrown: 'System.ComponentModel.Composition.Primitives.ComposablePartException' in System.ComponentModel.Composition.dll ("Cannot create an instance of type 'AccessibilityInsights.Extensions.GitHubAutoUpdate.AutoUpdate' because a constructor could not be selected for construction. Ensure that the type either has a default constructor, or a single constructor marked with the 'System.ComponentModel.Composition.ImportingConstructorAttribute'.") Exception thrown: 'System.ComponentModel.Composition.Primitives.ComposablePartException' in System.ComponentModel.Composition.dll ("Cannot create an instance of type 'AccessibilityInsights.Extensions.GitHubAutoUpdate.AutoUpdate' because a constructor could not be selected for construction. Ensure that the type either has a default constructor, or a single constructor marked with the 'System.ComponentModel.Composition.ImportingConstructorAttribute'.") Hyperlink: Activate Historical Debugging	0.45s		[25212] Main Thread

**Comment by DaveTryon** [comment]
@jalkire, this has been merged into master. Please close it out once you have the chance to regress it.
