### ISSUE TITLE
[BUG] ControlShouldNotSupportValuePattern should consider Name property

### ISSUE THREAD

**Issue by LiLoDavis** [Microsoft/accessibility-insights-windows#270]
**Current rule**
Currently looks for text controls that support the value pattern. Returns as uncertain instead of error.

**Proposed rule**
1. Look for text controls that support the value pattern.
2. Compare content of name and value.
3. Return error if name and value differ.

**Comment by neocln** [comment]
@RobGallo Based on MSDN, ValuePattern is not supported in Text Control. 
however, because there are cases of having value patterns in Text Control in some frameworks, we had it as warning than error. 
https://docs.microsoft.com/en-us/windows/desktop/winauto/uiauto-supporttextcontroltype
I would like to understand what this rule change is based on.

**Comment by karanbirsingh** [comment]
@LiLoDavis I checked in with @neocln & @RobGallo - since other rules ensure that an automation name must exist, the additional presence of a value pattern does not have high user impact - thus it is listed as 'uncertain'. The name/value comparison error is interesting and we can consider it if it is reflected in the MSDN docs

**Comment by karanbirsingh** [comment]
accidental close, marking as resolve instead
