### ISSUE TITLE
[BUG] ControlViewCalendarStructure should allow ListItem

### ISSUE THREAD

**Issue by LiLoDavis** [Microsoft/accessibility-insights-windows#271]
**Current rule**
The given element is expected to have the following structure: Calendar / (DataGrid and NoChild(Header) or == 1 and AnyChild(Header and (NoChild(HeaderItem) or == 7)) and NoChild(Button) or == 2 and ( > 0)).'

**Proposed rule**
The rule should allow ListItem.
See the documentation: https://docs.microsoft.com/en-us/windows/desktop/winauto/uiauto-supportcalendarcontroltype#typical-tree-structure

**Comment by RobGallo** [comment]
The docs at https://docs.microsoft.com/en-us/windows/desktop/WinAuto/uiauto-supportdatagridcontroltype say that DataGrids should have DataItems as their children. We agree with that and think the inclusion of ListItem in the Calendar documentation is an error. Therefore, this issue is not applicable.
