### ISSUE TITLE
[BUG] Link to release notes always goes to Production

### ISSUE THREAD

**Issue by DaveTryon** [Microsoft/accessibility-insights-windows#298]
**Describe the bug**
The link to the release notes always points to the production release notes, regardless of release channel

**To Reproduce**
1. Go to the What's new screen
2. Click on "go to to the latest release notes"
3. See error

**Expected behavior**
This should go either to the release notes for the Channel or the specific Release

**Actual behavior**
This goes to the releases notes on accessibilityinsights.io (which is always production)

**Screenshots or .GIF**

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Accessibility Insights for Windows Version: 1.1.0834.01

**Additional context**
Priority requested -

**Comment by AhmedAbdoOrtiga** [comment]
- Do we have a release note page for each channel or version to use as suggested in the "Expected behavior"?
- Also since the official place to download and use AI-Win is [AI-Win](https://aka.ms/accessibilityinsights-windows/download) which matches with the production release notes [Notes](https://accessibilityinsights.io/docs/en/windows/reference/releases), is this still a valid issue?
