### ISSUE TITLE
[Feature Request] Add Ability to Expand Nodes from UI Inspection Tree

### ISSUE THREAD

**Issue by enricotj** [microsoft/accessibility-insights-windows#333]
**Is your feature request related to a problem? Please describe.**
At the moment, if you have a UI element under inspection there is no way to dive deeper into its children nodes. You can get observe and navigate its top-level children, but nothing deeper.

**Describe the solution you'd like**
It would be nice to be able to dive deeper into children UI elements from the inspection window.

**Describe alternatives you've considered**
It is possible to inspect UI elements deeper in the tree on screen, but it will not let the user easily observe elements that may perhaps be hidden from the UI or collapsed.

**Comment by neocln** [comment]
@adrianaandreeva this request has been heard from the substantial number of users. 
could we create a feature for this in the next quarter?

**Comment by DaveTryon** [comment]
Current thinking: Add 2 options to the drop-down menu on the element. One allows one generation of children to the enumerated for this element, the other expands all descendants of the tree. We'll want to get input from @cheade on the specifics

**Comment by Sirisha-Kommushetty** [comment]
Simplest thing is to have a button to walk the whole tree. Let's connect with @cheade to get some inputs here.

**Comment by jalkire** [comment]
@Sirisha-Kommushetty Another option would be to add a "Show Descendants" menu item alongside "Show Ancestry": 
![image](https://user-images.githubusercontent.com/4615491/62171884-64359980-b2e5-11e9-841d-d0c32b658f91.png)

**Comment by Sirisha-Kommushetty** [comment]
@enricotj - We've looked into this and are exploring possible solutions.

**Comment by cheade** [comment]
@jalkire What's the difference between 'Show ancestry' and 'Show descendants'?

**Comment by enricotj** [comment]
Awesome! Thanks for all your great work! ^_^

**Comment by FalseLobster** [comment]
+1

I frequently find myself falling back to the legacy Inspect app just because I find it so much easier to navigate around the UIA tree.

I'd urge you against scoping this feature to just descendants.  What if I want to see siblings?  What if I want to see descendants of siblings?

**Comment by jalkire** [comment]
@cheade "Show ancestry" toggles displaying the hierarchy tree from the selected element all the way back to the root/desktop node:

Checked:
![image](https://user-images.githubusercontent.com/4615491/62500085-e1578780-b799-11e9-8342-8da6a61f8cb5.png)

Unchecked:
![image](https://user-images.githubusercontent.com/4615491/62500096-eae0ef80-b799-11e9-9c5c-e450b8fc241f.png)

In some ways, it is analogous to this feature request, except it allows inspecting higher up the tree rather than descending into the tree. 

On way to offer the requested functionality would be to add a menu item like "Show all descendants" which, if checked, would result in ai-win fully populating the descendants of the selected element in the hierarchy tree.

**Comment by cheade** [comment]
Can we replace "Show descendants" with "Show all descendants?" What's the benefit of having the two options?

**Comment by jalkire** [comment]
We don't currently have either--I didn't mean to suggest adding two new items. "Show descendants" or "Show all descendants" are two options for the text of the single new menu item I am suggesting.

**Comment by Sirisha-Kommushetty** [comment]
@cheade - We have some ideas on what we could do here. Can we run by UX interviews for the next steps.

**Comment by adarshrema** [comment]
+1 from @FalseLobster at [issue #685](https://github.com/microsoft/accessibility-insights-windows/issues/685).

**Comment by ChristoWolf** [comment]
+ 1 from me.
Also, I think it would be nice to extend this feature even further: It should be possible to visualize the whole UI automation tree similar to how it is visualized in inspect.exe.
This way, one could navigate to any element in any running application by clicking it in the UI tree instead of clicking the element in the UI.

**Comment by DaveTryon** [comment]
We want to pursue this, pending an approved design

**Comment by RobGallo** [comment]
Reopening based on a customer request.

**Comment by citelao** [comment]
This lead me to some false conclusions when trying to diagnose an issue my team faced. Because I couldn't hover an element, and because the UI did not indicate the parent element had children, I falsely concluded that the element was empty.

Using Ctrl+Shift+F7 and Ctrl+Shift+F8 "worked around" this issue, but this is a major blocker for me to replace Inspect.exe.

It's bothered me for years, but this time it actually caused me to misdiagnose something. Happy to give more help as needed :)!

**Comment by DaveTryon** [comment]
We want to pursue this. Let's try to get a 1-engineer spike to understand the options, including potentially using the updated UIA mechanisms

**Comment by spudthebud** [comment]
If anything can be done to improve navigating the UIA tree with keyboard arrow keys, I'd encourage it.  This involves exploring descendants too.  Inspecting a tree and having to use triple chorded keystrokes (e.g., control + shift +f*) is inefficient and ineffective.   And I support @citelao's idea for showing the whole tree wholistically, like in Inspect.

**Comment by DaveTryon** [comment]
Unfortunately, this is out of scope given our current priorities.

Thanks for using Accessibility Insights!

**Comment by citelao** [comment]
@DaveTryon Is this something you'd be open to contributions for?

This is a long-standing regression from `inspect.exe`, and makes it very difficult for people who work in accessibility, like me, to audit UI to make sure the whole tree is correct.

I have a hunch the initial design was based on Edge's behavior, but Edge is actively changing their accessibility UI to show the complete tree:

<img width="200" alt="Enable full-page accessibility tree in Edge Inspector" src="https://github.com/microsoft/accessibility-insights-windows/assets/432939/ab276ea9-5747-423a-9300-972485a36f0d">

Complete tree:

<img width="446" alt="Full-page accessibility tree in Edge Inspector" src="https://github.com/microsoft/accessibility-insights-windows/assets/432939/07bb87c0-3467-4e8a-9cf3-ad52b7925aec">
