### ISSUE TITLE
[BUG] Weird behaviour with display and Jaws

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-windows#379]
Please check whether the bug has [already been filed](https://github.com/Microsoft/accessibility-insights-windows/issues).

**Describe the bug**
When connected to a different screen and using Jaws, after running fastPass, the automated checks UI goes away

**To Reproduce**
1. turn on Jaws and connect to a different display
2. run automated checks in an app
3. UI dissapears

**Expected behavior**
UI works as expected without a screen reader

**Actual behavior**
UI dissapears

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809] (Get the version by running `winver` from the command line) Windows 10
 - Accessibility Insights for Windows Version: Canary
 - Target Application: [e.g. Chrome, Wildlife Manager] Wildlife Manager

**Additional context**
Found during demo.

**Comment by Sirisha-Kommushetty** [comment]
@jalkire - Could you prioritize this when Rob is in town.

**Comment by jalkire** [comment]
@Sirisha-Kommushetty Update on this. I have been able to repro the problem consistently on my machine, which is good and bad news. I have not been able to find a solution--our previous fix is no longer working. We've (mostly @flyingUnderTheRadar) spent a fair amount of time trying to mitigate this in the past with mixed results, so I'm not optimistic about finding a compromise-free solution. We can chat in person if you'd like some context around the issue.

**Comment by flyingUnderTheRadar** [comment]
Just to give some more context
@RobGallo - this is the one that we worked together to repro on your machine. 

We were able to fix it via [this PR](https://github.com/microsoft/accessibility-insights-windows/pull/114/files). The fix that worked (evidenced by @jalkire @ the CSUN demo) simply invalidates the mainwindow visual and forces a re render with the highest priority.

**Code around this has since changed and the issue has started reappearing**

As far as I can tell this seems to be a WPF issue (can be repro'd with other apps as well). 

In my opinion if we want to pick this up I would highly suggest getting the folks at WPF involved pretty early to better guide us.

**Comment by DaveTryon** [comment]
@ferBonnin, this should be in the next build (1.1.901.1, I believe)

**Comment by DaveTryon** [comment]
@ferBonnin, please regress using release https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.0904.01

**Comment by ferBonnin** [comment]
Cannot repro in my computer. Per conversation with @jalkire that could repro this in his computer, this release has fixed the issue.
