### ISSUE TITLE
[BUG] TextBox in a UWP app gives a false positive

### ISSUE THREAD

**Issue by ArchieCoder** [microsoft/accessibility-insights-windows#446]
Please check whether the bug has [already been filed](https://github.com/Microsoft/accessibility-insights-windows/issues).

**Describe the bug**
There is a false positive for TextBox in a UWP app. The tool reports: "The given ControlType must have the IsControlElement property set to TRUE". 

**To Reproduce**
See the video, it would be easy to understand. For information, the Narrator says correctly the Placeholder text. As you see in the video, typing something in the first text box will fix both text boxes!

**Expected behavior**
There should be no false positive issue.

**Actual behavior**
A false positive issue arises.

**Screenshots or .GIF**
Video: [TextBox.zip](https://github.com/microsoft/accessibility-insights-windows/files/3453084/TextBox.zip)

**Desktop (please complete the following information):**
Windows 10 1903

**Additional context**
Priority requested -

**Comment by flyingUnderTheRadar** [comment]
Hello Archie, 
Thank you for your report. 

Based on my conversations with my colleague, a textbox should have the `IsControlElement` set to `true`. This is used by screenreaders in different ways. 

Without access to your source code or the app we have no way of verifying whether this property on the textbox is initially set to `true`. Additionally once you type something in the box does this property change to true?

You can check this property by using the settings in the inspect view (right top in details / properties). Click on it and select `Include all properties that have values` and search for its value *before* and *after* typing something in. Let us know once you have been able to confirm that its a false positive !

**Comment by ArchieCoder** [comment]
As shown in the new screenshot, IsControlElement is not a property that exists for TextBox. It is not also included in AutomationProperties.

It is not even part of the detail pane like you have suggested.

![Insights](https://user-images.githubusercontent.com/1608424/62242314-e3d86c80-b3a8-11e9-90ef-d5380e52fbea.png)


![TextBox2](https://user-images.githubusercontent.com/1608424/62242071-66146100-b3a8-11e9-931b-73b1c7b3e251.png)

**Comment by iamrafan** [comment]
@ArchieCoder can you please share the ```(.a11ytest)``` file of the failure you are seeing? 

Please use the save button on the top left to export the test results
![image](https://user-images.githubusercontent.com/22068434/62244781-052f5d80-b395-11e9-89c0-4c0bae9ea477.png)

**Comment by ArchieCoder** [comment]
There you go: [TestResults 07-31-19.zip](https://github.com/microsoft/accessibility-insights-windows/files/3453740/TestResults.07-31-19.zip)

FYI, if you want access to my device, we can do a remote session with the Windows 10 tool: Quick Access

**Comment by flyingUnderTheRadar** [comment]
Thanks for the test file. Using the test file provided by you I can see (refer the GIF on how to view the property) that the property is indeed set to false meaning that the app is functioning correctly.
![FalsePositive](https://user-images.githubusercontent.com/45673569/62247633-12e7e180-b39b-11e9-8bba-72d34d4d74dc.gif)

I did a small sample UWP app and by default this value is set to true. Here are the results of a sample app with a textbox in it.
![image](https://user-images.githubusercontent.com/45673569/62248127-38291f80-b39c-11e9-8cd9-5bfdf8506364.png)

 The next question would be is there anything that you might be doing in the code that would cause this property to be over ridden?

**Comment by ArchieCoder** [comment]
1- Look at my video again. I do the test app, it shows the 2 errors and then I click refresh and it says no errors. It does not make any sense. I feel a bug here in the Insight tool
[Bug.zip](https://github.com/microsoft/accessibility-insights-windows/files/3457060/Bug.zip)

2- Here is the XAML code

<TextBox
            x:Uid="Login_Username"
            InputScope="EmailSmtpAddress"
            IsEnabled="{Binding IsLogging, Converter={StaticResource BooleanNegationConverter}}"
            IsSpellCheckEnabled="False"
            IsTextPredictionEnabled="False"
            Margin="0,12,0,0"
            Text="{Binding Username, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
            Width="320">

            <interactivity:Interaction.Behaviors>
                <behaviors:KeyUpEnterBehavior>
                    <behaviors:FocusAction
                        TargetObject="{Binding ElementName=PasswordBox}" />
                </behaviors:KeyUpEnterBehavior>
            </interactivity:Interaction.Behaviors>

        </TextBox>

3- There is a PlaceholderText that is set from Resoruces.resw

<data name="Login_Username.PlaceholderText" xml:space="preserve">
    <value>Email</value>
  </data>

4- The Narrator says correctly "Email"

5- Are you sure you tried on a UWP app? I do not see the IsControlElement property at all.

**Comment by flyingUnderTheRadar** [comment]
1. Yes @ArchieCoder - We are aware that the first time around the errors show up and the second time around they do not. This does not mean that the tool has a bug. In the a11ytest file that you have shared we can clearly see that the required property is set to false which is why the rule is flagging it. More info about why the rule is implementing it can be found [here](https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-supporttextcontroltype). 

Before we go any further I would highly suggest referring to the gif above and **make sure that you can see all properties in Accessibility Insights Windows app using the setting (you need to explicitly select `Include all properties that have values` . It's in the gif)** that I have shown in the GIF. Here it is again for reference 
![FalsePositive](https://user-images.githubusercontent.com/45673569/62247633-12e7e180-b39b-11e9-8bba-72d34d4d74dc.gif)
 
**Then run Automated tests twice.** 
- First do the run that throws the error and look for the `isControlElement` element. Based on the file that you shared with us we can see that this property is set to `false`. Which is why the tool is flagging it.
- Next type in something into the boxes and run the test and check the value of the same property. There might be something happening when you click on the box that sets this value to true. If it is set to `true` then the error should disappear. Can you share the a11ytest file from this run as well please?

2. This piece of code in isolation does not help us repro the issue. I have created a [sample app](https://github.com/flyingUnderTheRadar/SampleUWPApp) that you can view and verify. Please download the code and run it and see if the issue shows up on the sample app. In the sample app we can see that by default the `isControlElement` value is set to true. There is no explicit code that sets this value.
![image](https://user-images.githubusercontent.com/45673569/62322704-80a71280-b45a-11e9-9356-af3d7f24ca87.png)
![image](https://user-images.githubusercontent.com/45673569/62322748-9a485a00-b45a-11e9-9ec1-461c55e50698.png)

This indicates that either - 
-- Something in the code is overriding it. (Yes we are aware it is not directly settable, but there are ways to override this value)
-- UWP is, for some reason, starting with the property set to `false`.

3. Ok

4. Yes the narrator will say whatever is available to it. This does not mean that there isn't an issue. If an element is a control element but is not marked as such then it will not show up as a part of the control view when screenreaders use the UIAutomationTree.

5. Please refer to the sample app. The property is inherited. There might not be a straightforward way to set it but it is definitely settable. If you aren't doing anything special with the textbox then we guess that this issue stems from some oddity with the UWP framework and as such we should go ahead and file a bug with UWP.

**Comment by ArchieCoder** [comment]
Thanks for the prompt daily update, it is appreciated! Kudos on that.

I have good news and a bad news.

After 2 hours of trials and errors, I have found the culprit, but I don't understand why.

Are you ready? You'll have to try yourself to believe it. The presence of the PasswordBox makes the tool trigger false-positive. In your provided sample, I added a PasswordBox. Use the tool and you will see it backfires on the TextBox.
[MainPage.zip](https://github.com/microsoft/accessibility-insights-windows/files/3459410/MainPage.zip)

I will let you investigate from there. In another part of my app, there is a TextBox where the page does not contain a PasswordBox and I presume there is another similar issue.

---

The link that you gave me: https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-supporttextcontroltype is about win32 apis and nothing to do with UWP.

Good luck and I'm looking forward to your investigation.

**Comment by ArchieCoder** [comment]
Hi @flyingUnderTheRadar, we have an audit with Msft next week. If you could let me know if my finding is a bug in the tool or in the UWP system, I would appreciate.

Thank you!

**Comment by flyingUnderTheRadar** [comment]
Hi @ArchieCoder 

I have added a password box in the[ sample code](https://github.com/flyingUnderTheRadar/SampleUWPApp). You can download and play around with the app there. Yes, we were able to reproduce the issue now. Thank you for the steps to reproduce. 

However this does not change our earlier conclusion. See the below GIF. We can still see that the `isControlElement` property is set to `false` when the app starts up. The tool is supposed to flag this and is doing so rightly based on our understanding.

![FalsePositive-2](https://user-images.githubusercontent.com/45673569/62574265-ee817e80-b84c-11e9-84d2-295eadaecdcf.gif)

Should you want to raise a flag with UWP [this might be a good place to start](https://wpdev.uservoice.com/forums/110705-universal-windows-platform)

Thanks a lot for reporting this issue. :-)

**Comment by ArchieCoder** [comment]
FYI, the Windows Dev user voice is the worse place to share bugs. This place is dead and the team does not monitor it anymore.

Sébastien
________________________________
