### ISSUE TITLE
Color contrast analyzer auto detect has high confidence but wrong colors

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-windows#537]
**Describe the bug**
The color contrast analyzer's auto detect has high confidence but the wrong colors.

**To Reproduce**
1. Open Wildlife Manager 2.0 (demo app).
2. Use CCA auto detect contrast ratio of the label that says "Current Animals:".

**Expected behavior**
Auto detect identifies the foreground (Color 1) as #8D2D00.

**Actual behavior**
Actual background color is #000000.

**Screenshots or .GIF**
![AI-Win CCA wrong colors and high confidence](https://user-images.githubusercontent.com/45569509/64882974-1c5b9f00-d613-11e9-8ba3-f67f6d5c1772.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1903] 
 - Accessibility Insights for Windows Version: Prerelease Build (1.1.984.5) / Canary channel
 - Target Application: Wildlife Manager
 - Target Application Version: 2.0

**Comment by ferBonnin** [comment]
Leaving this bug open to hear feedback from more users on the auto-detect color contrast. We might want to add telemetry to examine how often the toggle gets turned on/off too

**Comment by DaveTryon** [comment]
@adarshrema, I've looked at this, and it's basically a side effect of antialiasing and relatively low resolution. Text that looks like it's obviously black on white is a lot more complicated when you zoom the bitmap to show it as individual pixels, which is how the algorithm sees it:

![image](https://user-images.githubusercontent.com/45672944/97643883-133fb400-1a06-11eb-965f-92310048a349.png)

As the code scans from left to right, the most common color transitions are the rust-colored pixels that form the vertical lines of the 'u' and the second 'r', followed by the slightly lighter shade that forms the left edges of the 'i' and the 'm'.

The current bits report this as mid confidence instead of high, which is an improvement but not really a fix. We might be able to adjust our config options to improve some results, but our overall options may be limited, due simply to the limited amount of data that is available for analysis. This may be a case where we need to consider a color contrast algorithm that is optimized for antialiased text.

**Comment by LiLoDavis** [comment]
As of today, using AI-Win version 1.1.1369.1, auto-detect for this text still shows incorrect color and high confidence.
