### ISSUE TITLE
[Issues] What is "Text pattern" issue of Windows Form TextBox element? 

### ISSUE THREAD

**Issue by v-lga-hub** [microsoft/accessibility-insights-windows#605]
1. There always have a failure when automated check a textbox element in Windows Forms page.
Fix the following:
1. Make sure the element has the appropriate ControlType property for its function.
2. **If the current ControlType is correct, modify the element to support the Text pattern.**

2. I noticed that if i test the textbox element in a WPF project, there isn't this issue.

So **Is this an accessibility issue? if so, what is means "Text pattern" and how to fix it in the windows Forms page?**

[AccessibilityFixes.zip](https://github.com/microsoft/accessibility-insights-windows/files/3738439/AccessibilityFixes.zip)
[TestResults 10-17-19.zip](https://github.com/microsoft/accessibility-insights-windows/files/3738447/TestResults.10-17-19.zip)

**Comment by DaveTryon** [comment]
@v-lga-hub, what you're seeing here is the same issue that is reported at https://github.com/dotnet/winforms/issues/1588 (last updated on October 8th). It represents a shortcoming in the Windows Forms textbox control. We don't have any specific visibility to know when a fix will become available.

The issue itself stems back to [Section 508, subsection 502.3.10](https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/single-file-version#502-interoperability-assistive-technology), which states "A list of all actions that can be executed on an object shall be programmatically determinable." In this case, the Windows Forms textbox doesn't expose the [UI Automation Text pattern](https://docs.microsoft.com/en-us/dotnet/framework/ui-automation/ui-automation-textpattern-overview), which is the pattern associated with text manipulation, and should be exposed on a textbox.

There are at least 3 ways to respond to this reported issue (in increasing risk)
1. Leave your code as is for now, and wait for an updated version of Windows Forms (that contains a fix), then upgrade to the new version of Windows forms. You'll need to include this reported issue in your [VPAT](https://www.section508.gov/sell/vpat) until the issue is actually fixed.
2. Use the Windows Forms RichTextBox control instead of the regular TextBox control. This may require other changes due to restrict the richer feature set of the RichTextBox.
3. Consider using a framework other than Windows Forms (nuclear option).

Please let us know if you have any additional questions. Thanks!

**Comment by v-lga-hub** [comment]
@DaveTryon thanks a lot for your detailed explanation.
