### ISSUE TITLE
AI for Desktop tool doesn't show UI property details with Live Inspect 'Element' option

### ISSUE THREAD

**Issue by Ajaz4193** [microsoft/accessibility-insights-windows#642]
AI for Desktop doesn't recognize the individual elements through LIVE INSPECT option for  the below applications - 

https://www.axure.com/
https://benchmarks.ul.com/pcmark10
https://www.sidefx.com/
https://marmoset.co/toolbag/
http://pixologic.com/

Using Live Inspect option either Entire Application/Element, it does not show any details of the focused elements/sections under Live Inspect  details.

Attached snapshot for reference - 
![AIforDesktop](https://user-images.githubusercontent.com/40019907/69366377-1b666f80-0c4b-11ea-9d1e-14de110f20e6.png)

**Comment by DaveTryon** [comment]
Hi, @Ajaz4193 !

  Accessibility Insights is built on the Windows UI Automation framework, which is the same framework that is used for screen readers like Windows Narrator, [NVDA](https://www.nvaccess.org/download/), and [JAWS](https://support.freedomscientific.com/Downloads/JAWS). These tools work very well with standard UI controls, because standard UI controls expose the data that UI Automation needs to work properly. Custom controls don't expose UI Automation unless it's explicitly added to the control, and these apps rely heavily on custom controls that ignore the conventions of UI Automation. I wasn't able to check all of the apps that you references, but I _was_ able to confirm that both Axure and Marmoset use custom controls that expose no information to UI Automation. To screen readers and Accessibility Insights, these apps look like a collection of a few empty boxes. The apps are fundamentally non-accessible.

  There's a certain irony that the accessibility tools report no accessibility problems, but it falls back to a lack of any usable information. It would be wonderful to have a heuristic that says "your app doesn't seem to do anything", but it's very hard to reconcile heuristics with the "no false positives" approach that we try to achieve. It also calls out the fact that certain classes of problems are beyond the ability of the tools to determine, and that some level of human testing is still required. In this case, the human testing would immediately reveal the fact that the application is not accessible.

  Here are some easy ways to check for custom controls:
1. Run [Spy++](https://docs.microsoft.com/en-us/visualstudio/debugger/introducing-spy-increment?view=vs-2019), which is freely available as part of Visual Studio Community edition. As you move the window target around the application, if it looks like a big empty box, that's a strong warning.
2. Run Narrator (part of Windows 10) or [NVDA](https://www.nvaccess.org/download/) and listen to what the screen reader reports. This is essentially the experience that a screen reader user would have, so if the screen reader isn't reading anything for you, it wouldn't be reading anything for your customer, either.

  Thanks for your interest in Accessibility Insights for Windows!

**Comment by ferBonnin** [comment]
@Ajaz4193 can you please let us know if this answers your question?
