### ISSUE TITLE
[BUG] Installer error 2755

### ISSUE THREAD

**Issue by pcable** [microsoft/accessibility-insights-windows#776]
**Describe the bug**
I attempted to install the msi but received error 2755.

**To Reproduce**
1. Download installer from https://aka.ms/accessibilityinsights-windows/download
2. Attempt install
3. Get error 2755

See attached log

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Accessibility Insights for Windows Version: 1.1

[installLog.log](https://github.com/microsoft/accessibility-insights-windows/files/4543150/installLog.log)

**Comment by dbjorge** [comment]
Hi @pcable,

We're sorry you're hitting this issue! We haven't been able to reproduce the problem you're seeing, and unfortunately the error information in the log file is fairly generic. The most specific information we think is relevant is `Error 2755:  Server returned unexpected error 110 attempting to install package`, which has many potential causes.

Some options to try:

* Download the installer again and double check that it isn't corrupted (the SHA256 hash for AccessibilityInsights.msi v1.1.1198.01 should be `2CE37A774B36B7B832AD5A08CCE0F593D9CB8DDE361AEA5F0C5F786ED320F96A`)
* Try installing to/from the `C:\` drive, rather than `D:\` like the log suggests you've tried already
* If you have any RAMDisk software installed (particularly ImDisk), try disabling it temporarily
* Ensure you're up to date on Windows Updates

Let us know if any of those solve your problem. If not, can you share which version of Windows you're trying to install on? You can find this by pressing "Windows + R" and typing `winver` to get a dialog like this:

![screenshot of winver dialog with version number highlighted](https://user-images.githubusercontent.com/376284/80524494-90e61280-8944-11ea-83f9-ef36fd841b0b.png)

**Comment by pcable** [comment]
Thanks. Turns out all msi's on my machine are failing with code 2755.
