### ISSUE TITLE
copy-to-clipboard behavior is not consistent

### ISSUE THREAD

**Issue by adarshrema** [microsoft/accessibility-insights-windows#887]
Spinning this off #880.

Confirm that copying (Ctrl+C) text from automated checks result is working as expected while,
* Selecting an individual item from automated checks result list to copy failure details
* Selecting different parts of UI Automation Tree view to copy details like properties, description

Once this behavior is confirmed, we will update documentation accordingly.

**Comment by DaveTryon** [comment]
The problem here is that AIWin is copying on KeyUp of Ctrl+C, while the standard for Windows apps is to copy on KeyDown of Ctrl+C. Either will work if the keyboard pattern is Ctrl Down, C Down, C Up, Ctrl Up. However, decades of muscle memory have trained my left hand to do Ctrl Down, C Down, Ctrl Up, C up. When that happens, Ctrl is no longer down when the KeyUp is received for C, and copy doesn't trigger. I've created a PR to trigger copy on KeyDown of C, so we're consistent with the way the OS handles Copy.

**Comment by DaveTryon** [comment]
Confirmed in build 1.1.1320.1
