### ISSUE TITLE
[BUG] show issue “Localized control type and ControlType must not both "custom"

### ISSUE THREAD

**Issue by st8711000** [microsoft/accessibility-insights-windows#931]
Please check whether the bug has [already been filed](https://github.com/Microsoft/accessibility-insights-windows/issues).

**Describe the bug**
Describe the bug
Accessibility tool show issue “The ControlType and LocalizedControlType must not both be set to "custom" "  

**To Reproduce**
1. Download source code: https://drive.google.com/file/d/1qC2BVsTVWUGFI4xQtY9xVnjiBzviDkxZ/view?usp=sharing
2. Launch DataGrid.exe in DataGrid\DataGrid\bin\Debug folder
3. Run accessibility insights tool with the entire app setting(DataGrid.exe)
4. Accessibility insights tool testing result appear error message: “The ControlType and LocalizedControlType must not both be
    set to "custom""
Note:  MSFT suggest upgrade Net Framework to 4.7.2,this issue can be resolved, however, if my project not upgrade Net 
           Framework,whether other method to fix the issue.

**Expected behavior**
No issue appear

**Actual behavior**
Appear error message: “The ControlType and LocalizedControlType must not both be set to "custom""

**Screenshots or .GIF**

**Desktop (please complete the following information):**
 -OS: Windows 10 1903 18362
 -Accessibility Insights for Windows Version: v1.1
 -Target Application: WPF app
 -Target Application Version: NA

**Additional context**
Priority requested -

**Comment by st8711000** [comment]
Update issue screenshot 

<img width="812" alt="Screenshot_1" src="https://user-images.githubusercontent.com/14719836/93049738-326fc580-f694-11ea-8e99-1bc66697c7b7.png">

**Comment by lisli1** [comment]
@st8711000, thanks for using Accessibility Insights for Windows!

After investigating this issue, we have found that this particular [issue with the DataGridCell was fixed in .NET Framework 4.7.1](https://docs.microsoft.com/en-us/dotnet/framework/whats-new/whats-new-in-accessibility#whats-new-in-accessibility-in-net-framework-471). 

If you are unable to update your .NET Framework, we recommend looking into [Accessibility Switches](https://docs.microsoft.com/en-us/dotnet/framework/whats-new/whats-new-in-accessibility#accessibility-switches), which allow your application to take advantage of new accessibility features without having to update your .NET Framework version: "You can configure your app to opt into accessibility features if it targets .NET Framework 4.7 or an earlier version but is running on .NET Framework 4.7.1 or later." 

We tried this with the attached application and it no longer showed the issue. Is this something that would work for you?

**Comment by st8711000** [comment]
Thanks for your help.
Can you provide source code or example for Accessibility Switches if I not upgrade .NET Framework to 4.7.1

**Comment by DaveTryon** [comment]
@st8711000, there are a couple of ways you could add these flags. Given your sample project as a starting point, you can add the following lines (copied from https://docs.microsoft.com/en-us/dotnet/framework/whats-new/whats-new-in-accessibility#accessibility-switches) inside your existing app.config file as a sibling to the startup node:
```
    <runtime>
        <!-- AppContextSwitchOverrides value attribute is in the form of 'key1=true|false;key2=true|false  -->
        <AppContextSwitchOverrides value="Switch.UseLegacyAccessibilityFeatures=false;Switch.UseLegacyAccessibilityFeatures.2=false;Switch.UseLegacyAccessibilityFeatures.3=false" />
    </runtime>
```

This change allows more recent .NET versions to use the most recent accessibility behavior in framework-owned controls, instead of the legacy behavior. It's a good practice to always include these flags, since updates to the framework frequently include accessibility fixes.

I'm assigning this bug back to you. Please close it out at your convenience. Thanks!

**Comment by st8711000** [comment]
hi DaveTryon
Based on your feedback, my project can resolve this issue
Thanks

**Comment by DaveTryon** [comment]
@st8711000, I'm closing out this issue based on your response. Thanks!
