### ISSUE TITLE
[General Question] How did you initialize inner UIautomation elements at "Chrome_RenderWidgetHostHWND"?

### ISSUE THREAD

**Issue by xWSWx** [microsoft/accessibility-insights-windows#949]
What i do:
1. Run application, "Microsoft Teams", for example
2. Run "Accessibility Insights"
3. Move mouse on "Microsoft Teams", we get "Chrome Legacy Window"
4. After any mouse click (left/right) on target programm ("Microsoft Teams") provoke rebuild UI tree
5. Then UIautomation technology can get all inner UI elements in browser, "Accessibility Insights" too

I studied your source code very carefully, but not found code, that provide rebuilding (or, initializing?) inner UI elements.
It wonderfull magic!

1. Could you tell me - how you do that?
2. Why the transformation will take place only after a mouse click?

**Comment by dbjorge** [comment]
Thanks for your interest in our code! The logic you're looking for actually lives in the [axe-windows](https://github.com/microsoft/axe-windows) library that this repository uses as a dependency, not in this repository. Through axe-windows, Accessibility Insights for Windows acts as a UI Automation Client to view the accessibility properties of applications being tested. We use a [UIAutomation TreeWalker](https://docs.microsoft.com/en-us/dotnet/api/system.windows.automation.treewalker?view=netcore-3.1) to view the tree of elements in the processes being scanned.

Some good starting points might be:

* [UI Automation Client Programmer's Guide](https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-clientportal)
* [How-To Topics for UI Automation Clients](https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-howto-topics-for-uiautomation-clients)
* [axe-windows code for obtaining the UI Automation root element of a different process](https://github.com/microsoft/axe-windows/blob/ea0d94a39cb79912a789417885f8200fb13a76c1/src/Desktop/UIAutomation/A11yAutomation.cs#L47)

Since this question is more about how to use UI Automation than an issue with Accessibility Insights for Windows, we're going to mark the issue as closed; if you have more specific questions, we encourage you to make a post on Stack Overflow with the `ui-automation` tag.

Thanks!
